USE SCHEMA SAMPLEDB.DEMO;
INSERT INTO EMPLOYEE (NAME, DEPT, AGE)
VALUES ('pavan', 'IT', 30);
INSERT INTO EMPLOYEE (NAME, DEPT, AGE)
VALUES ('krishna', 'IT', 30);
INSERT INTO EMPLOYEE (NAME, DEPT, AGE)
VALUES ('nag', 'FINANCE', 29);
INSERT INTO EMPLOYEE (NAME, DEPT, AGE)
VALUES ('guru', 'FINANCE', 29);