name: snowflake-devops-demo

#Controlls when the the action will run
on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'
   
  # Allows you to run this workfow manually from Actions tab
  workflow_dispatch:
  
jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
	
    steps:
      #Checks out your repository under $GITHUBWORKSPACE, so your job can access it
      - name: Checkout Repository
	uses: actions/checkout@v2
		
      - name: Use Python 3.8.x
	uses: actions/setup-python@v2.2.1
	with:
	  python-version: 3.8.x
		  
      - name: Run schemachange
	env:
		  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
		  SF_USERNAME: ${{ secrets.SF_USERNAME }}
		  SF_ROLE: ${{ secrets.SF_ROLE }}
		  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
		  SF_DATABASE: ${{ secrets.SF_DATABASE }}
		  SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
		  
		run: |
		  echo "GITHUBWORKSPACE: $GITHUBWORKSPACE"
		  python --version
		  echo "Step 1: Installing schemachange"
		  pip install schemachange
		  
		  echo "Step 2: Running schemachange"
		  schemachange -f $GITHUBWORKSPACE/dbscripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
		  
